#!/usr/bin/env python3
"""CUDA-Libs aus den pip-nvidia-Wheels für TensorFlow sichtbar machen.

TensorFlow (CUDA 12) findet die unter site-packages/nvidia/*/lib liegenden
Shared Objects nicht automatisch, wenn PyTorch (CUDA 13) dieselben Namespaces
mitnutzt. PyTorch bringt eigene RPATHs mit — TF nicht.

Nutzung:
  python scripts/nvidia_cuda_path.py --print-ld   # Pfad für LD_LIBRARY_PATH
  python scripts/nvidia_cuda_path.py --install    # sitecustomize + Kernel-Env
"""

from __future__ import annotations

import argparse
import ctypes
import json
import os
import site
from pathlib import Path


def nvidia_lib_dirs() -> list[Path]:
    roots = site.getsitepackages() + ([site.getusersitepackages()] if site.getusersitepackages() else [])
    dirs: list[Path] = []
    for root in roots:
        nvidia = Path(root) / "nvidia"
        if not nvidia.is_dir():
            continue
        for lib in sorted(nvidia.glob("*/lib")):
            if lib.is_dir():
                dirs.append(lib)
    return dirs


def ld_library_path() -> str:
    return ":".join(str(p) for p in nvidia_lib_dirs())


def preload_nvidia_libs() -> int:
    """Lädt nvidia-*.so mit absolutem Pfad (wirkt auch ohne LD_LIBRARY_PATH)."""
    loaded = 0
    for lib_dir in nvidia_lib_dirs():
        for lib in sorted(lib_dir.glob("*.so*")):
            if lib.suffix == ".a" or ".so" not in lib.name:
                continue
            try:
                ctypes.CDLL(str(lib), mode=ctypes.RTLD_GLOBAL)
                loaded += 1
            except OSError:
                pass
    return loaded


def install_sitecustomize() -> Path:
    target = Path(site.getsitepackages()[0]) / "sitecustomize.py"
    target.write_text(
        '''"""Auto-generated by scripts/nvidia_cuda_path.py --install. Do not edit."""
# Preload pip nvidia CUDA libs so TensorFlow can dlopen them (GPU).
try:
    from pathlib import Path
    import ctypes
    import site

    for root in site.getsitepackages():
        nvidia = Path(root) / "nvidia"
        if not nvidia.is_dir():
            continue
        for lib_dir in sorted(nvidia.glob("*/lib")):
            for lib in sorted(lib_dir.glob("*.so*")):
                if ".so" not in lib.name:
                    continue
                try:
                    ctypes.CDLL(str(lib), mode=ctypes.RTLD_GLOBAL)
                except OSError:
                    pass
except Exception:
    pass
''',
        encoding="utf-8",
    )
    return target


def patch_jupyter_kernel(kernel_name: str = "py-uv_keras-xai") -> Path | None:
    kernel_json = Path.home() / ".local/share/jupyter/kernels" / kernel_name / "kernel.json"
    if not kernel_json.is_file():
        return None
    data = json.loads(kernel_json.read_text(encoding="utf-8"))
    env = data.setdefault("env", {})
    path = ld_library_path()
    existing = env.get("LD_LIBRARY_PATH", "")
    # Unsere nvidia-Pfade voranstellen, Rest behalten
    parts = [p for p in path.split(":") if p]
    for p in existing.split(":"):
        if p and p not in parts:
            parts.append(p)
    env["LD_LIBRARY_PATH"] = ":".join(parts)
    kernel_json.write_text(json.dumps(data, indent=1) + "\n", encoding="utf-8")
    return kernel_json


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print-ld", action="store_true", help="LD_LIBRARY_PATH-Fragment ausgeben")
    parser.add_argument("--install", action="store_true", help="sitecustomize + Jupyter-Kernel patchen")
    parser.add_argument("--preload", action="store_true", help="Libs jetzt laden und Anzahl drucken")
    args = parser.parse_args()

    if args.print_ld:
        print(ld_library_path())
        return
    if args.preload:
        print(f"preloaded={preload_nvidia_libs()}")
        return
    if args.install:
        sc = install_sitecustomize()
        print(f"wrote {sc}")
        kj = patch_jupyter_kernel()
        print(f"patched kernel: {kj}" if kj else "kernel.json not found (run make setup first)")
        return
    parser.print_help()


if __name__ == "__main__":
    main()
