#!/usr/bin/env python3
"""CUDA-Libs aus den pip-nvidia-Wheels für TensorFlow sichtbar machen.

TensorFlow braucht CUDA-12-Libs unter site-packages/nvidia/*/lib.
PyTorch bringt zusätzlich CUDA-13-Wheels mit (u.a. nvidia/cu13/lib) und hat
eigene RPATHs — TF nicht.

Wichtig: CUDA-13-Pfade dürfen NICHT in LD_LIBRARY_PATH / sitecustomize landen.
Treiber 550.x unterstützt max. CUDA 12.4; cu13 → cudaErrorInsufficientDriver.

Nutzung:
  python scripts/nvidia_cuda_path.py --print-ld   # Pfad für LD_LIBRARY_PATH
  python scripts/nvidia_cuda_path.py --install    # sitecustomize + Kernel-Env
"""

from __future__ import annotations

import argparse
import ctypes
import json
import site
from pathlib import Path

# CUDA-13-Bäume und typische Torch-only-Namespaces überspringen.
# TF nutzt die cu12-Wheels (gleiche nvidia/<pkg>/lib-Pfade ohne cu13/).
_SKIP_PARTS = frozenset({"cu13", "nvshmem", "cusparselt"})


def _is_tf_relevant(lib_dir: Path) -> bool:
    parts = set(lib_dir.parts)
    if parts & _SKIP_PARTS:
        return False
    # Explizite CUDA-13-Runtime-Bäume
    if any(p.startswith("cu13") for p in lib_dir.parts):
        return False
    return lib_dir.is_dir()


def nvidia_lib_dirs() -> list[Path]:
    roots = site.getsitepackages() + ([site.getusersitepackages()] if site.getusersitepackages() else [])
    dirs: list[Path] = []
    for root in roots:
        nvidia = Path(root) / "nvidia"
        if not nvidia.is_dir():
            continue
        for lib in sorted(nvidia.glob("*/lib")):
            if _is_tf_relevant(lib):
                dirs.append(lib)
    return dirs


def ld_library_path() -> str:
    return ":".join(str(p) for p in nvidia_lib_dirs())


def preload_nvidia_libs() -> int:
    """Lädt nvidia-*.so mit absolutem Pfad (wirkt auch ohne LD_LIBRARY_PATH)."""
    loaded = 0
    for lib_dir in nvidia_lib_dirs():
        for lib in sorted(lib_dir.glob("*.so*")):
            if lib.suffix == ".a" or ".so" not in lib.name:
                continue
            try:
                ctypes.CDLL(str(lib), mode=ctypes.RTLD_GLOBAL)
                loaded += 1
            except OSError:
                pass
    return loaded


_SITECUSTOMIZE = '''"""Auto-generated by scripts/nvidia_cuda_path.py --install. Do not edit."""
# Preload pip nvidia CUDA *12* libs so TensorFlow can dlopen them (GPU).
# Skip cu13 (PyTorch): drivers like 550.x only support CUDA <= 12.4.
try:
    from pathlib import Path
    import ctypes
    import site

    _SKIP = frozenset({"cu13", "nvshmem", "cusparselt"})

    for root in site.getsitepackages():
        nvidia = Path(root) / "nvidia"
        if not nvidia.is_dir():
            continue
        for lib_dir in sorted(nvidia.glob("*/lib")):
            if set(lib_dir.parts) & _SKIP:
                continue
            for lib in sorted(lib_dir.glob("*.so*")):
                if ".so" not in lib.name:
                    continue
                try:
                    ctypes.CDLL(str(lib), mode=ctypes.RTLD_GLOBAL)
                except OSError:
                    pass
except Exception:
    pass
'''


def install_sitecustomize() -> Path:
    target = Path(site.getsitepackages()[0]) / "sitecustomize.py"
    target.write_text(_SITECUSTOMIZE, encoding="utf-8")
    return target


def patch_jupyter_kernel(kernel_name: str = "py-uv_keras-xai") -> Path | None:
    kernel_json = Path.home() / ".local/share/jupyter/kernels" / kernel_name / "kernel.json"
    if not kernel_json.is_file():
        return None
    data = json.loads(kernel_json.read_text(encoding="utf-8"))
    env = data.setdefault("env", {})
    path = ld_library_path()
    existing = env.get("LD_LIBRARY_PATH", "")
    # Unsere (cu12) nvidia-Pfade voranstellen; alte cu13-Einträge verwerfen
    parts = [p for p in path.split(":") if p]
    for p in existing.split(":"):
        if not p or p in parts:
            continue
        if "/nvidia/cu13/" in p or p.rstrip("/").endswith("/cu13/lib"):
            continue
        if any(f"/nvidia/{name}/" in p for name in ("nvshmem", "cusparselt")):
            continue
        parts.append(p)
    env["LD_LIBRARY_PATH"] = ":".join(parts)
    kernel_json.write_text(json.dumps(data, indent=1) + "\n", encoding="utf-8")
    return kernel_json


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print-ld", action="store_true", help="LD_LIBRARY_PATH-Fragment ausgeben")
    parser.add_argument("--install", action="store_true", help="sitecustomize + Jupyter-Kernel patchen")
    parser.add_argument("--preload", action="store_true", help="Libs jetzt laden und Anzahl drucken")
    args = parser.parse_args()

    if args.print_ld:
        print(ld_library_path())
        return
    if args.preload:
        print(f"preloaded={preload_nvidia_libs()}")
        return
    if args.install:
        sc = install_sitecustomize()
        print(f"wrote {sc}")
        kj = patch_jupyter_kernel()
        print(f"patched kernel: {kj}" if kj else "kernel.json not found (run make setup first)")
        print("LD (cu12 only):", ld_library_path())
        return
    parser.print_help()


if __name__ == "__main__":
    main()
